### ISSUE TITLE
Standard CSS style formatting

### ISSUE THREAD

**Issue by misterManSam** [fractalhexagon/blueprint#2]
What are you using to format your CSS? For instance, I sometimes use a tool like [Dirty Markup](http://www.dirtymarkup.com/) before every commit when working with others so that it will always look the same. This avoids highlighting huge areas of whitespace for every small change.

**Comment by wplanetary** [comment]
The thing is, like I said, I mostly took the code from another userstyle which I thought was incomplete. I added in a bit of Materialize.css. So that I can see in real-time what are the changes I make, I used the Stylish textbox, which doesn't fix syntax problems. Guess I should give it a go for Dirty Markup, or just use the Brackets beautifier plugin.

**Comment by misterManSam** [comment]
Cool, let's use the Brackets plugin so that every commit looks consistent.
